### ISSUE TITLE
[Feature] multiple namespace support

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#511]
## Feature: multiple namespace support

The feature is outlined at https://github.com/openfaas/faas-netes/issues/433, which can be used for comments, questions, and suggestions.

The use-case is: multiple namespaces, single installation, i.e. `dev/staging`, `team-a/team-b`, `client-a/client-b`.

## Checklist:

* [x] Allow `.` in paths for faas-provider https://github.com/openfaas/faas-provider/pull/26
* [x] Allow `.` in paths for faas/gateway https://github.com/openfaas/faas/pull/1315
* [x] Update "direction functions" behaviour in gateway to allow namespace in path
* [x] Check/Update behaviour for auto-scaling via alerts https://github.com/openfaas/faas/pull/1316
* [x] Check the way Prometheus metrics are recorded
* [x] Define optional RBAC role for ClusterRole https://github.com/openfaas/faas-netes/commit/e2c013bfefbef9d224ce01ebb56f63b116d90ded
* [x] Update faas-netes CRUD to use namespace detected or passed in #513 #519
* [x] Update faas-netes to populate namespace in "get" endpoint - https://github.com/openfaas/faas-netes/pull/512
* [x] Update faas-netes, faas and faas-provider with list namespaces endpoint https://github.com/openfaas/faas/pull/1318 #518 https://github.com/openfaas/faas-provider/pull/27
* [x] Add a list functions flag / endpoint which enumerates all valid namespaces
* [x] Add namespace filtering to only OpenFaaS namespaces
* [x] Update CLI to become namespace-aware for Function CRUD https://github.com/openfaas/faas-cli/pull/694
* [x] Check/Update [nats-queue-worker](https://github.com/openfaas/nats-queue-worker) so that it is namespace-aware 
* [x] Check/Update [connector-sdk](https://github.com/openfaas-incubator/connector-sdk/) so that it is namespace-aware https://github.com/openfaas-incubator/connector-sdk/pull/36
* [x] Document approach for testing e2e
* [x] Update docs repo where required to document multiple-namespaces 

CLI

* [x] Deploy via `--namespace` for single function
* [x] Deploy via stack.yml with multiple functions - https://github.com/openfaas/faas-cli/issues/737
UI https://github.com/openfaas/faas/issues/1379

* [x] UI - add namespace selector
* [x] UI - add "all namespaces" option

Secrets

* [x] Update faas-netes for CRUD for secrets to use namespace detected or passed 

Logs
* [x] Update faas-netes to use namespace detected or passed for logs 

Docs

* [x] Add overview and testing instructions page https://docs.openfaas.com/reference/namespaces/
* [x] Add to CLI --help pages
* [x] Add to YAML reference page

Triggers

* [x] Support in event-connector SDK https://github.com/openfaas-incubator/connector-sdk/issues/50
* [x] Support in faas-idler https://github.com/openfaas-incubator/faas-idler/issues/37
* [x] Support in cron-connector https://github.com/openfaas/cron-connector/issues/6

OpenFaaS operator

* [x] Copy approach/changes from faas-netes https://github.com/openfaas-incubator/openfaas-operator/issues/92

* [x] Basic logs
* [x] Endpoint load-balancing
* [x] Multiple-namespace support

## Diagram

![](https://user-images.githubusercontent.com/6358735/62921801-a230c400-bda1-11e9-8406-017b48f9af6c.png)

## Test out the patches so far

Test e2e with this Gist and the following patches: https://gist.github.com/alexellis/3b285ca0952d4cef48ca5dbff7e4e288

**Comment by viveksyngh** [comment]
I will work on updating faas-netes to make secrets API namespace aware and add namespace flag to the secrets command to CLI.

**Comment by jonatasbaldin** [comment]
hey @viveksyngh, I'm working on the `faas-netes`, `faas-provider` and `faas` for that already 🙈 

would u like to focus on the CLI?

for the `GET /system/secrets` I'm gonna pass a `namespace` query parameter and for the other ones (POST, PUT, DELETE) I'll pass a new `namespace` field in the body.

what do u think?

**Comment by jonatasbaldin** [comment]
I have a POC working locally already, will cleanup and push today :)

**Comment by viveksyngh** [comment]
> or the GET /system/secrets I'm gonna pass a namespace query parameter and for the other ones (POST, PUT, DELETE) I'll pass a new namespace field in the body.

I think that should be fine.  Please let me know if you need any help.

I can work on the CLI.

**Comment by jonatasbaldin** [comment]
Here's the PRs from the Secrets:

- [faas-provider #28](https://github.com/openfaas/faas-provider/pull/28)
- [faas #1334](https://github.com/openfaas/faas/pull/1334)
- [faas-netes #530](https://github.com/openfaas/faas-netes/pull/530)

❤️
